src/nextsec/firewall/__init__.py, src/nextsec/utils/__init__.py, tests/test_firewall.py, tests/test_utils.py
Above methods have been moved under utils sinece
they do not strictly belong to the firewall.
=> refactor: move get_device_name and get_interface_name

.github/workflows/build-doc.yml, README.md, src/nethsec/firewall/__init__.py, src/nethsec/utils/__init__.py, tests/test_firewall.py, tests/test_utils.py
This PR is required for the implementation of the following features:
- installation templates: create a configuration template for a firewall which can easily be reproducible in similar scenarios
- automatic configuration of known services, currently known services are:
- OpenVPN RoadWarrior, action: change listening port or add a new instance
- OpenVPN tunnel, action: change listening port or add a new instance
- Wireguard, action: change listening port or add a new instance
- Dedalo hotspot: enable/disable the service
- Nginx: change management UI port
- configuration wizards like:
- first configuration with 3 zones lan, wan and guests: automatically create the blue zone for guests
- first configuration with strict mode where all traffic is closed from lan to wan: enable the access of …
=> Template database and new ns_ options

src/nethsec/mwan/__init__.py, src/nethsec/utils/__init__.py, tests/test_mwan.py
=> feat: added mwan apis

src/nethsec/dpi/__init__.py, tests/test_dpi.py
Due to latest changes, a prefix append to applications was missed during the PR review.
This fixes the issue.
=> fix: fixed wrong app name scheme in rules

src/nethsec/utils/__init__.py, tests/test_utils.py
List all unassigned devices.
This function will be used inside ns.dedalo API and can be used in the future for the interfaces APIs
Card: https://trello.com/c/d1f2GLNK/149-lib-list-unassigned-devices
See also: https://github.com/NethServer/nethsecurity/pull/197
=> utils: add get_unassigned_devices

setup.py, src/nethsec/firewall/__init__.py, src/nethsec/ipsec/__init__.py, tests/test_firewall.py, tests/test_ipsec.py
Card: https://trello.com/c/4QXj5LpC/181-ipsec-tunnel-configuration
=> fead: add ipsec lib

src/nethsec/mwan/__init__.py
If label is not defined for a policy, the code was throwing a key error.
=> fix: mwan, index_rules do not fail if label is not defined

src/nethsec/firewall/__init__.py, tests/test_firewall.py
Create a new `add_default_ipv6_rules` method which can be used by the ns.devices APIs.
The new method adds required ipv6 rules only if not they already exists.
=> Firewall lib: default IPv6 rules

src/nethsec/dpi/__init__.py, tests/test_dpi.py
The netifyd configuration is now updated at every network configuration change.
Use netifyd internal_if and external_if options to retrieve the list of available interfaces.
Card: https://trello.com/c/ShnFDa4G/135-netifyd-listening-changes
=> dpi: list devices configured inside netifyd

src/nethsec/dpi/__init__.py
If netifyd has never been configured, return at least all lan interfaces
=> dpi: device_list fallback

src/nethsec/firewall/__init__.py, tests/test_firewall.py
Add basic nat functions:
- list_nat_rules
- add_nat_rule
- edit_nat_rule
- delete_nat_rule
These functions are meant to be used inside the APIs: https://github.com/NethServer/nethsecurity/pull/326
Added also netmap rules, see APIs: https://github.com/NethServer/nethsecurity/pull/334
Card: https://trello.com/c/tavYHA5b/283-nat-rules-source-and-destination-netmap
=> firewall: implement nat and netmap rules

src/nethsec/ipsec/__init__.py, tests/test_ipsec.py
If the interface option is set to a non-exiting interface, IPsec tunnels are not created.
This is a common scenario after the migration.
Please note that this change will take effect on non-migrated machines.
=> ipsec: remove interface option

src/nethsec/utils/__init__.py
Avoid the following error when listing IPs
of pppoe-xxxx devices.
```
File "/usr/lib/python3.11/site-packages/nethsec/utils/__init__.py", line 506, in get_all_wan_ips
ret.append({"device": f'{interface.replace("@","")} ({device})', "ipaddr": ip})
^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```
NethServer/nethsecurity#540
=> utils: fix list of pppoe IPs

src/nethsec/inventory/__init__.py, tests/test_inventory.py
Fixing following issues:
- wrong database fetch in subscription environments
- revamped data from network
- revamped data from mwan
Query to retrieve stats of number of WANs in every firewall
```sql
WITH wan_interface_number AS (SELECT id,
jsonb_path_query(to_jsonb(data), '$.facts.features.network.wan.*')::integer as interface_by_ipv_count
FROM installations
WHERE updated_at > NOW() - interval '7 day'),
total_interfaces_per_id AS (SELECT id,
SUM(interface_by_ipv_count) as total_interfaces
FROM wan_interface_number
GROUP BY id)
SELECT COUNT(id), total_interfaces
FROM total_interfaces_per_id
GROUP BY total_interfaces;
```
=> fix(inventory): small fixes and improvements

src/nethsec/utils/__init__.py
Previously, the function was not returning the interface associated to a PPPoE device
NethServer/nethsecurity#571
=> utils: fix get_interface_from_device

src/nethsec/mwan/__init__.py, tests/test_mwan.py
This pull request fixes a validation issue in the `store_rule` and `store_policy` functions. Previously, the functions did not validate the length of the name parameter, which could lead to errors. This PR adds a check to ensure that the name length is not greater than 15 characters. If the length exceeds 15 characters, a `ValidationError` is raised. This improvement ensures that the functions handle name length validation correctly and prevents potential issues.
https://github.com/NethServer/nethsecurity/issues/556
the PR does not need to validate [A-Z,a-z,0-9,_] because get_id sanitizes it https://github.com/NethServer/python3-nethsec/blob/923b5b4c2bdee128249a4d09ca26c402399aef57/src/nethsec/utils/__init__.py#L60
NOTE: 
- we need to test the ID and not only the name because the ID is …
=> Fix name length validation in store_rule and store_policy functions

src/nethsec/mwan/__init__.py, tests/test_mwan.py
This pull request adds a new `sticky` parameter to the `index_rules`, `store_rule` and `edit_rule` functions in the `__init__.py` file of the `mwan` module. The `sticky` parameter allows specifying whether to use sticky connections for the rule. The parameter accepts values of '0' or '1', and any other value will raise a validation error.
NethServer/nethsecurity#581
=> Add sticky option to index_rules, store_rule and edit_rule functions

src/nethsec/mwan/__init__.py, tests/test_mwan.py
This pull request replaces hyphens with colons in the source and destination ports of the MWAN module. This ensures consistency and compatibility with other parts of the codebase.
https://github.com/NethServer/nethsecurity/issues/580
=> Replace hyphens with colons in MWAN source and destination ports

src/nethsec/users/__init__.py, tests/test_users.py
If the description field is not passed as parameter, the value of the field must be preserved
NethServer/nethsecurity#592
=> users: fix description unwanted update

src/nethsec/mwan/__init__.py, tests/test_mwan.py
Fixing issue where mwan can be labeled incorrectly when only one interface is configured
Ref:
- https://github.com/NethServer/nethsecurity/issues/606
=> fix(mwan): wrong type labeling for policies

src/nethsec/users/__init__.py, tests/test_users.py
The new `user_bind_dn` can be used to override the authentication behavior of OpenVPN server.
See:
- NethServer/nethsecurity#602
- NethServer/nethsecurity#594
- https://github.com/NethServer/nethsecurity-ui/pull/303
=> users: add support for user_bind_dn

src/nethsec/reverse_proxy/__init__.py
This header is a de-facto standard. Still, some applications may not work correctly with it, notably WebTop.
Remove the header from new reverse_proxy configuration to have the same behavior of NethServer 7: this should prevent regressions.
NethServer/nethsecurity#622
=> reverse_proxy: remove X-Forwarded-Proto header

src/nethsec/reverse_proxy/__init__.py
By default, max_body_size is 1MB which is different from NethServer 7 were the maximum size was set to 1GB.
Raise the limit to 1GB for new reverse proxies to retain the old behavior and limit regressions.
=> reverse_proxy: increase max_body_size

src/nethsec/objects/__init__.py
Add `type` and `subtype` in `list_domain_sets` output. These attributes are used by the UI to recognize object types.
Ref:
- https://github.com/NethServer/nethsecurity/issues/689
=> fix(objects): add type & subtype in list_domain_sets

src/nethsec/mwan/__init__.py, src/nethsec/objects/__init__.py, tests/test_mwan.py, tests/test_objects.py
- remove domain set support
- prevent usage of IPv6 objects
References:
- Issue: NethServer/nethsecurity#671
- Changes used by: https://github.com/NethServer/nethsecurity/pull/712
=> mwan: fix object support

src/nethsec/conntrack/__init__.py
Avoid error like:
```
File "/usr/lib/python3.11/site-packages/nethsec/conntrack/__init__.py", line 39, in __parse_meta_connection_tag
result['packets'] = counters.find('packets').text
^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```
The error could be caused by a connection like this one:
```
unknown  2 598 src=0.0.0.0 dst=224.0.0.1 [UNREPLIED] src=224.0.0.1 dst=0.0.0.0 mark=0 use=1
```
=> conntrack: make sure counters is set

src/nethsec/dpi/__init__.py, tests/test_dpi.py
Publishing method `load_protocols`.
Change needed by https://github.com/NethServer/nethsecurity/pull/779
=> refactor: set to public load_protocols method

src/nethsec/firewall/__init__.py, tests/test_firewall.py
Allow editing of the log field.
NethServer/nethsecurity#807
=> firewall: zones, add log field

src/nethsec/inventory/__init__.py, tests/test_inventory.py
Add more statistics to the inventory
the [json object](https://gist.github.com/stephdl/d3d2197fb9f5905837cd2003c6d800ea) output 
json sample
```json
"netifyd": {
"enabled": false
},
"snmp": {
"enabled": true
},
"ddns": {
"enabled": true
},
"nathelpers": {
"count": 2,
"enabled": true
},
"certificates_info": {
"custom_certificates": {
"count": 1
},
"acme_certificates": {
"count": 1,
"issued": 0,
"pending": 1
}
},
"database_stats": {
"main": {
"users": 2
}
},
"dhcp_server": {
"count": 1,
"static_leases": 1,
"dynamic_leases": 0,
"dns_records_count": 2,
"dns_forwarder_enabled": true
},
"firewall_stats": {
"firewall": {
"port_forward": 1,
"nat": {
"masquerade": 1,
"snat": 1,
"accept": 1
},
"netmap": {
"source": 1,
"destination": 1
},
"rules": {
"forward": 1,
"input": 9,
"output": 1
}
}, …
```
=> Inventory: advanced usage statistics

src/nethsec/mwan/__init__.py, tests/test_mwan.py
Ref:
- https://github.com/NethServer/nethsecurity/issues/853
=> fix(mwan): adding default last_resort when creating policy

src/nethsec/objects/__init__.py
Ensure that the total characters used by a domain set in the dnsmasq configuration file do not exceed 1024.
Refs:
- https://github.com/NethServer/nethsecurity/issues/877
- https://github.com/NethServer/nethsecurity-ui/pull/430
=> fix: validation of domain sets domains

src/nethsec/utils/__init__.py
Add `get_public_ip_addresses` function, useful to retrieve the public address(es) associated to a private IP address / network interface.
Ref:
- https://github.com/NethServer/nethsecurity/issues/890
=> feat(utils): add get_public_ip_addresses function

src/nethsec/inventory/__init__.py, tests/test_inventory.py
Introduce functions to list DNS feeds from a JSON file and to retrieve the ad block status, enhancing inventory management capabilities.
https://github.com/NethServer/nethsecurity/issues/928
=> Add functions to list DNS feeds and retrieve ad block status

src/nethsec/users/__init__.py
Users inside a remote LDAP are usually matched in case-insensitive mode.
Make sure to always force the username to lower case to avoid mismatch when the remote LDAP has names in uppercase (like AD): this change will fix access for OpenVPN users using the external LDAP.
Note that such users are already imported in lower case inside the users db.
NethServer/nethsecurity#966
=> fix(users): force user name to lower case

src/nethsec/firewall/__init__.py, tests/test_firewall.py
Update the `is_zone` function to recognize '*' as a valid zone name, enhancing its flexibility in zone validation.
https://github.com/NethServer/nethsecurity/issues/1012
=> Firewall: Allow any zone as valid input for is_zone function

src/nethsec/inventory/__init__.py
Implement functionality to retrieve and return statistics for WireGuard interfaces, including the number of instances and peers associated with each interface.
https://github.com/NethServer/nethsecurity/issues/987
```json
"wiregard": {
"instances": 2,
"statistics": [
{
"server": "wg1",
"peers": 2,
"ns_user_db": "main"
},
{
"server": "wg2",
"peers": 0,
"ns_user_db": "ldap"
}
]
},
"mac_ip_binding": {
"disabled": 1,
"soft-binding": 0,
"hard-binding": 1
},
"snort": {
"enabled": true,
"policy": "security",
"oink_enabled": false,
"disabled_rules": 2,
"bypass_src_ipv4": 2,
"bypass_src_ipv6": 0,
"bypass_dst_ipv4": 0,
"bypass_dst_ipv6": 0
},
```
=> feat(inventory): track new Snort, WireGuard and MAC binding features

src/nethsec/inventory/__init__.py
Include a count of suppression rules in the Snort facts for better inventory management.
NethServer/nethsecurity#987
=> feat(inventory):  add suppress rule to snort statistics 

src/nethsec/inventory/__init__.py
Correct a typo in the function name and improve the counting of disabled MAC bindings by considering only valid interfaces.
https://github.com/NethServer/nethsecurity/issues/987
=> feat(inventory): count disabled mac binding only on valid interfaces

src/nethsec/users/__init__.py
Ignore username case when looking for a user inside users database.
**NOTE**
This change will make username validation more restrictive: two or more users with the same name but different case (e.g. `Goofy` and `goofy`) won't be allowed anymore.
Ref:
- https://github.com/NethServer/nethsecurity/issues/1039
=> fix(users): ignore username case

src/nethsec/users/__init__.py
Require users to input the old password when changing it.
While this change impacts only the change password form for your own account, this makes sure that from another user you cannot change the root password.
Ref:
- https://github.com/NethServer/nethsecurity/issues/1023
=> feat(users): add function to check for old password match

src/nethsec/firewall/__init__.py, tests/test_firewall.py, tests/test_inventory.py
=> feat(firewall): add log limits

src/nethsec/inventory/__init__.py
If you have a 1.5.1 updated with the latest packages, inventory couldn't be sent due to missing configuration.
The ubus calls return None, that don't have a `length`, which caused the sync to fail.
=> fix(inventory): inventory couldn't be sent due to missing config
