src/nethsec/firewall/__init__.py
tests/test_firewall.py

Added `list`, `add` and `delete` APIs for zones
Added `list` for forwardings

Zone/Forwarding APIs

---

src/nethsec/utils/__init__.py
tests/test_utils.py

The functions could be used from API scripts
to raise generic and validation errors

utils: add validation errors functions

---

.gitignore
src/nethsec/firewall/__init__.py
src/nethsec/utils/__init__.py
tests/test_firewall.py
tests/test_utils.py

Add `edit_zone` api
Other changes:
- `create_zone`: ensure a zone with the same name doesn't exist
- Add .gitignore
- Fix minor typos

firewall: add edit_zone api

---

setup.py
src/nethsec/dpi/__init__.py
src/nethsec/utils/__init__.py
tests/test_dpi.py
tests/test_utils.py

Added dpi methods
- index application/protocol
- index rules
- add rule
- delete rule
- edit rule

feat: apis for netifyd

---

src/nethsec/dpi/__init__.py
tests/test_dpi.py

Found an issue with current implementation, was setting a `interface` field, however a `device` was needed.
While at it:
- Added `list_devices` method
- Added additional `device` field in `list_rules`

fix: dpi wrong param definition in configuration

---

src/nethsec/dpi/__init__.py
tests/test_dpi.py

I've been asked to add few features to the `dpi` APIs
- added meta fields, which contains `total` entries and `last_page` available
- updated behaviour when the "popular application" is missing from the default list

DPI enhancements

---

src/nethsec/dpi/__init__.py
tests/test_dpi.py

Due to unsure format for `netify-categories.json`, this will hopefully support them both.

refactor: refactored dpi categories for both old and new files

---

src/nethsec/dpi/__init__.py
tests/test_dpi.py

Card: https://trello.com/c/BxNF70JT/168-dpi-add-exclusions-to-rule-global
See also: https://github.com/NethServer/nethsecurity/pull/238

dpi: add global exemptions

---

setup.py
src/nethsec/ovpn/__init__.py
tests/test_ovpn.py

Reuse the same code for OpenVPN roadwarrior and OpenVPN tunnels
Card: https://trello.com/c/uJW5AAwp/178-openvpn-rw

Add OpenVPN lib

---

builder/build.sh
setup.py
src/nethsec/users/__init__.py
src/nethsec/utils/__init__.py
tests/test_users.py
tests/test_utils.py

Card: https://trello.com/c/uJW5AAwp/178-openvpn-rw
See also: https://github.com/NethServer/nethsecurity/pull/245

User management

---

src/nethsec/users/__init__.py
tests/test_users.py

Changes for list-databases:
- rename `id` field to `name`
- add `uri` to the field list for ldap database
Other changes:
- add `get_database` function

Improvements for UI

---

src/nethsec/firewall/__init__.py

If the zone has a random id the old logic was not finding the correct zone id.
Example of faulty zone:
config zone 'ns_bf7b0ec4'
option name 'hotspot'

fix: firewall, fix edit_zone zone id retrieval

---

src/nethsec/mwan/__init__.py

Added way to clear completely mwan configuration
Ref: https://trello.com/c/IfL8EN6X/306-multiwan-default-policy-single-wan

feat(mwan): added clear_config api

---

src/nethsec/firewall/__init__.py
tests/test_firewall.py

Fix adding/editing firewall rules on any protocol
Card: https://trello.com/c/ggpLSzJ1/318-firewall-all-protocols-rule

Fix firewall rules on any protocol

---

setup.py
src/nethsec/firewall/__init__.py
src/nethsec/utils/__init__.py
tests/test_firewall.py

For some part of application, it's needed to have aliases hidden away
Card: https://trello.com/c/LFCTBvU7/351-aliases-among-interfaces

Hide aliases

---

setup.py
src/nethsec/utils/__init__.py

Another alias change, has been found after previous merge
Card: https://trello.com/c/LFCTBvU7/351-aliases-among-interfaces

feat: adding alias exclusion to `get_all_wan_devices`

---

src/nethsec/users/__init__.py

Sort list of users before returning it.
On remote LDAP database, make sure the sorting is done after retrieving all users using paged search.

users: sort output list

---

src/nethsec/mwan/__init__.py

Ref: NethServer/nethsecurity#469

feat(mwan): sync mwan defaults to active interfaces

---

setup.py
src/nethsec/inventory/__init__.py
tests/test_inventory.py

Functions for inventory and phonehome
Card: https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=57950688

Add inventory package

---

src/nethsec/mwan/__init__.py
tests/test_mwan.py

Ref: https://github.com/NethServer/nethsecurity/issues/605

refactor(mwan): increase metrics distancing

---

setup.py
src/nethsec/ldif/__init__.py
src/nethsec/users/__init__.py
tests/test_users.py

users: new LDIF parsing tool

---

src/nethsec/reverse_proxy/__init__.py

Fixing issue with reverse proxy format

fix(reverse proxy): remove incorrect client_max_body_size format

---

src/nethsec/mwan/__init__.py

Removing singleton only HostSets

fix(mwan): adding CIDR/IPlists to MWAN objects

---

src/nethsec/reverse_proxy/__init__.py

The allow field is valid only inside location records.
NethServer/nethsecurity#723

reverse_proxy: fix allow field

---

src/nethsec/reverse_proxy/__init__.py

Ref:
- https://github.com/NethServer/nethsecurity/issues/723

reverse_proxy: fixing positional argument

---

src/nethsec/firewall/__init__.py

Ref:
- https://github.com/NethServer/nethsecurity/issues/895

fix(firewall): add ns_link reference to ipset used by redirect

---

src/nethsec/firewall/__init__.py
tests/test_firewall.py

Ref:
- https://github.com/NethServer/nethsecurity/issues/894

fix(firewall): fixing duplicate creation of ipsets

---

src/nethsec/firewall/__init__.py

Ref:
- https://github.com/NethServer/nethsecurity/issues/919

fix(firewall): remove the ipset only if needed

---

src/nethsec/ovpn/__init__.py

Do not set a route for the bond management network
NethServer/nethsecurity#931

fix(ovpnrw): ignore bond management IP

---

setup.py
src/nethsec/snort/__init__.py

Imported from: https://github.com/jasonish/py-idstools/
Related PR: https://github.com/NethServer/nethsecurity/pull/885
**REVIEWER NOTE:** please ignore the the conflict on setup, we are going to merge only the commit that imports snort library

Add snort parser library

---

src/nethsec/firewall/__init__.py

Introduce a function to verify if a given name corresponds to an existing zone
https://github.com/NethServer/nethsecurity/issues/899

feat(firewall): add is_zone function to check if a zone still exist

---

src/nethsec/firewall/__init__.py

Correct the logic for checking zones in the `is_zone` and `list_rules` functions to ensure accurate zone validation.
NethServer/nethsecurity#899

feat(firewall): fix is_zone function to check if a zone still exist

---

src/nethsec/inventory/__init__.py

Introduce a new function to verify the existence of the backup passphrase file and retrieve its last modified date.
https://github.com/NethServer/nethsecurity/issues/988

feat(inventory): check backup passphrase existence and date

---

src/nethsec/firewall/__init__.py

Ref:
- https://github.com/NethServer/nethsecurity/issues/989

fix(firewall): allow rules with same src/dest zone

---

src/nethsec/dpi/__init__.py

Allowing usage of VLANs due to request by:
- https://github.com/NethServer/nethsecurity/issues/1101

feat(dpi): added vlans in listed devices

---

.github/workflows/scans.yml

Added dependency management and vuln scanning through Trivy.

ci: added SBOM scanning

---

src/nethsec/firewall/__init__.py

Do not read uci backup filed created by opkg
NethServer/NethSecurity#1134

fix(firewall): ignore backup files
